title: Slate theme
description: Slate is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate

title : "Equipe 13"
description : "TP5 : Initiation Ã  GitHub Pages"
